### PR TITLE
Update extension.driver.php

### PR DESCRIPTION
**Pull request by cmnstmntmn**
Fix date format for **last_execution** column

### CODE REVIEW

**Comment by nitriques** [comment]
Hum more testing would be needed before I merge this in since I think that datetime formats are localized in MySQL... But thanks!

**Comment by nitriques** [comment]
Well looks like I am wrong! http://dev.mysql.com/doc/refman/5.1/en/datetime.html Thanks for the fix!

Does it fixes the problem in 1.0 also ?

**Comment by cmnstmntmn** [comment]
yes it does, i am using 1.0 (but i've made the update into 1.1 branch)

i modified based on 
https://github.com/symphonycms/symphony-2/commit/6796f9c1dcfec8fdb0ea32a910487783f931e5c6

**Comment by nitriques** [comment]
Awesome! I'll release 1.1.1 with this fix ASAP. Thanks again!

**Comment by nitriques** [comment]
1.1.1 is out! https://github.com/DeuxHuitHuit/backend_action/releases/tag/1.1.1

**Pull request merged**
